swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '
        <h1>HTML Injection : Test_minsait</h1>
       '
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
